# Generated by Django 5.2.3 on 2025-07-08 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_video_dislikes_video_likes_alter_channel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='watched_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
