# Generated by Django 5.2.3 on 2025-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='channel_subscribers', to='youtube.channel'),
        ),
    ]
